### ISSUE TITLE
Todo`s 20 Dec 2023

### ISSUE THREAD

**Issue by raviKrishnuduVenna** [raviKrishnuduVenna/work-day-planner#1]
- [x]  3  Hours Code Review
- [ ]  3  Hours Learn OpenAI
- [ ]  2 Hours of Next.js
- [ ]  2 Hours of Tailwind Practice
